### ISSUE TITLE
onRemove() handler not included in dist

### ISSUE THREAD

**Issue by evolkmann** [el/infobox-control#1]
Hi @el,
first of all thanks for creating this library!

I noticed today that the `onRemove` handler is not included in the compiled `dist` files.

You introduced the handling in https://github.com/el/infobox-control/commit/7decb75524d2a278f63aab8a075b28baf2e1c59d, but maybe forgot to build and publish a new version?

**Comment by el** [comment]
Ohh, I guess it wasnt uploaded. It should be up to date now.
